server:
 port: 8081

spring:
 application:
   name: gateway

 cloud:
  gateway:
   server:
    webmvc:
     routes:
      - id: producto-service
        uri: lb://producto-service
        predicates:
         - Path=/api/v1/producto/**, /api/v1/items/**, /api/v1/mermas/**, /api/v1/ubicaciones/**
      - id: prooveedores-service
        uri: lb://proveedores-service
        predicates:
         - Path=/api/v1/detallerecepcion/**, /api/v1/ordenrecepcion/**, /api/v1/proveedor/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/